name: jojo
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'
  #sdk: '>=2.19.0-146.2.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  intl: ^0.18.0
  google_fonts: ^3.0.1
  line_awesome_flutter: ^2.0.0
  future_progress_dialog: ^0.2.1
  flutter_lints: ^2.0.0
  get: ^4.6.5
  hexcolor: ^3.0.1
  font_awesome_flutter: ^10.3.0
  share_plus: ^6.3.0
  csc_picker: ^0.2.6
  sn_progress_dialog: ^1.0.9
  country_picker: ^2.0.19

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/logos/
    - assets/logos/slogan.png
    - assets/logos/sloganblancorange.png
    - assets/images/image1.png
    - assets/logos/jojoblancorange.png
    - assets/images/camiongrand.png
    - assets/images/camionmoyen.png
    - assets/images/camionpetit.png

  fonts:
    - family: LouisGeorge
      fonts:
        - asset: fonts/Louis-George-Cafe-Light.ttf
  #         style: italic
    - family: GeoSans
      fonts:
        - asset: fonts/GeosansLight.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
